//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalDiary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Memory
    {
        public int memoryid { get; set; }
        [DisplayName("Date")]
        public string date { get; set; }
        [DisplayName("Image")]
        public string imagepath { get; set; }
        [DisplayName("Experience")]
        public string experience { get; set; }
        [DisplayName("Thoughts")]
        public string thoughts { get; set; }
        [DisplayName("Comments")]
        public string comments { get; set; }
        [DisplayName("Modification Date")]
        public string modifydate { get; set; }
        [DisplayName("Importance")]
        public string importance { get; set; }
        public int userid { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public virtual User User { get; set; }
    }
}
